[tool.poetry]
name = "how-to-use-poetry"
version = "0.1.0"
description = ""
authors = ["Shailesh Padalwar <shaileshpadalwar12345@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
